### PR TITLE
Create Hello world .py

### PR DESCRIPTION
**Pull request by cyberdev25**

### CODE REVIEW

**Review by BhuvaneshHingal — CHANGES_REQUESTED** [review]
Hello @cyberdev25! Thanks for contributing. Before I can merge these changes just a small request, kindly change the folder's name from practice to your name.

**Comment by cyberdev25** [comment]
Hey @Bhuvanesh! , I have changed the name of the folder. Kindly review it and thanks for such a quick response on my contribution.

**Review by BhuvaneshHingal — APPROVED** [review]
Looks Good 👍🏻

**Comment by cyberdev25** [comment]
> Looks Good 👍🏻

Thanks for merging it 😀

**Pull request merged**
