### PR TITLE
hey bro plz approve it

### PR DESCRIPTION
**Pull request by hacky502boy**
hi bro this one whom you mailed last night. So now plz approve it

### CODE REVIEW

**Review by BhuvaneshHingal — CHANGES_REQUESTED** [review]
@hacky502boy **Kindly understand that there's no need to change the markdown file format and doing minor changes will not count your contributions towards Hacktoberfest.**
Please follow the steps given inside the [README.md file](https://github.com/BhuvaneshHingal/HELLO-WORLD/blob/master/README.md), make a folder with your name, then add some programs (to print Hello World) inside that and then send a Pull Request. All the necessary details on what changes are to be made + how to make a PR are given inside the README.md file, please go through it.
***Still if you need any other help you can ping me***

**Comment by hacky502boy** [comment]
Bhai you said that we can make a slight change in program and can get
approved so,I did what u said I simply make a change I program

**Comment by BhuvaneshHingal** [comment]
>Bhai you said that we can make a slight change in program and can get
approved so,I did what u said I simply make a change I program

I never said to make any "slight change". However, you could make a slight change but it should be valid.
image
Line 5: You made the heading size smaller (of which there is no need and it simply disrupts the formatting style)
Line 8: You changed it to the plural form which is grammatically incorrect.
This repository is to contribute a hello world program. You can look how other people have contributed.

**Comment by BhuvaneshHingal** [comment]
Also @hacky502boy & @hacky503boy if you are making a PR for contributing towards Hacktoberfest, don't worry I'm not closing your Pull Request, hence it will be counted as a valid PR for the event. If I close this then it will become invalid. 
But try to understand, I cannot merge these changes as the changes made by you are not required.

**Comment by hacky502boy** [comment]
hey bro i understand that these are not required but u just merge it and
than remove it.
But plz approve it












       Thanks
           &
       Regards
Kumar Sales Budaun
Mob-8474923524
        8475023524

**Comment by BhuvaneshHingal** [comment]
@hacky502boy Done

**Pull request merged**
