### PR TITLE
Added Hello World Programs

### PR DESCRIPTION
**Pull request by sudeepshukla930**
Added 6 **Hello World** Program in 

1. C
2.  C++
3.  Java
4.  Python
5. Javascript
6. HTML

### CODE REVIEW

**Review by BhuvaneshHingal — CHANGES_REQUESTED** [review]
Everything's great just the JavaScript file is empty. Kindly add the code so that it can be merged.
image

**Comment by sudeepshukla930** [comment]
> Everything's great just the JavaScript file is empty. Kindly add the code so that it can be merged.
> image

 @BhuvaneshHingal Hey, I have updated the js file .Sorry for that mistake. Waiting to get merged

**Comment by sudeepshukla930** [comment]
@BhuvaneshHingal ..hey can you please review , and merge with hacktoberfest accepted..

**Review by BhuvaneshHingal — APPROVED** [review]
Looks Good 👍🏻

**Pull request merged**
